[package]
name = "wave_timeline"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
piston2d-graphics = "0.10.0"
pistoncore-input = "0.7.0"
piston-rect = "0.1.0"

[dev-dependencies]
piston_window = "0.22.0"
# anything that goes with piston_window.
pistoncore-sdl2_window = "0.15.1"
